import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/Footer'
import  Avatar from '../components/Avatar';
import AppsIcon from '@mui/icons-material/Apps';
import { IconButton } from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import KeyboardVoiceIcon from '@mui/icons-material/KeyboardVoice';
import CameraAltIcon from '@mui/icons-material/CameraAlt';
import Link from 'next/link';
import { useRef } from 'react';
import { useRouter } from 'next/router';

export default function Home() {
  const rout = useRouter();
  const searchInputRef = useRef(null);

  const search = (a) => {    
    a.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;

    rout.push(`/search?term=${term}`);
  };

  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex justify-between w-full p-5 text-sm text-gray-700'>
        {/*left */}
        <div className='flex space-x-4 items-center '>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>
        {/*right */}
        <div className='flex space-x-3 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>
          {/*icon*/}
          <IconButton>
          <AppsIcon className='h-10 w-10 rounded-full cursor-pointer hover:bg-gray-100'/>
          </IconButton>
          {/*avatar*/}
          <Avatar url={"https://res.cloudinary.com/chuckmaster/image/upload/v1663961707/myportfolio_img/myemoji_huclxl.jpg"} className={undefined}/>
        </div>
      </header>
      {/*body*/}
      <form action="" className='w-full flex-grow flex flex-col justify-center items-center'>
        <Image src="https://res.cloudinary.com/chuckmaster/image/upload/v1667550515/myportfolio_img/google_cyz52k.png"
        width={300} height={300} alt="google"/>
        <div className='border border-gray-300  p-2 flex items-center justify-center w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full px-5 py-3 sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon className='text-gray-500'/>
          <input ref={searchInputRef} type="text" className='focus:outline-lime-200 flex-grow'/>
          <KeyboardVoiceIcon className=' text-blue-500 mx-2'/>
          <CameraAltIcon className='text-red-500'/>
        </div>
        <div className='mt-5 flex flex-col w-1/2 space-y-2 justify-center sm:space-y-2 sm:flex-row sm:space-x-4'>
          <button onClick={search} className='btn'>Google Search</button>
          <button onClick={search} className='btn'>Im Feeling Lucky</button>
        </div>
        <div className='mt-5'>
          <h1>Goodle offered in: <span className='text-blue-600'><Link href={"/"}>Español (Latinoamerica)</Link></span></h1>
        </div>
      </form>
   

     <Footer/>
    </div>
  )
}
